### ISSUE TITLE
ADD: Aggregate Donate Synth tx into Saver Yield

### ISSUE THREAD

**Issue by thorchain-admin** [thorchain/thorchain-explorer-v2#154]
All of these are Saver Payouts, which happen every block, aggregate into a single pane and show better info

![image](https://github.com/thorchain/thorchain-explorer-v2/assets/41812729/e13ce3c8-c3bd-4be1-b1f9-c3d87e9fa0dd)

**Comment by HooriRn** [comment]
Will be gone on the next Midgard release.
